spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: ${PORT:8080}

logging:
  level:
    com.lumo: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
